### PR TITLE
Update ProductsController.cs

### PR DESCRIPTION
**Pull request by noufionline**
Change Tracking is not working unless the following code added.

### CODE REVIEW

**Comment by tonysneed** [comment]
The purpose of ModifiedProperties is to allow for partial updates. If it isn’t set then all the properties will be updated by Entity Framework.

**Comment by noufionline** [comment]
Hi @tonysneed ,

I tried to pass in a put request using postman but unfortunately, the product is always null.
```
{
    "ProductName": "Gravad lax (Updated using Put)",
    "UnitsInStock": 12,
    "ModifiedProperties":["ProductName","UnitsInStock"]
}
```

if I pass without ModifiedProperties it works perfectly. Any thoughts?

**Comment by tonysneed** [comment]
Usually this is a serialization issue.  Json.Net doesn't like something about your payload.  I'm attempting to replicate the issue (waiting for an rc-2 package update from @lelong37).

**Comment by lelong37** [comment]
image

Done..

**Comment by lelong37** [comment]
URF.Core.Sample has been upgraded to URF.Core RC2 NuGet packages.

**Comment by lelong37** [comment]
btw, in parallel to @tonysneed's troubleshooting, @noufionline have you tried to see if your POST with Postman on our live URF.Core demo in Azure:

https://github.com/urfnet/URF.Core.Sample

1.  http://northwind-web.azurewebsites.net/index.html
2.  http://northwind-api.azurewebsites.net/odata/Products (verb: GET)
3. http://northwind-api.azurewebsites.net/odata/Products({Id}) (verb: POST, PATCH & DELETE)
e.g. http://northwind-api.azurewebsites.net/odata/Products(37) ({id}, replaced with actual ProductId

We're actually using PATCH verb, so we only have to send properties that are actually updated vs. the entire entity (payload) over the wire perf reasons (serialization & deserialization). However the signatures for both ProductsController.Patch and ProductsController.Post are identical other than the HTTP verbs and to @tonysneed 's point the JSON payloads between the two should be fairly similar or even identical. 

Here's screenshot with Chrome DevTools open while editing a ProductName for one of the products.

image

**Comment by noufionline** [comment]
Hi, @lelong37 I have tried even on the Azure site. 
Here is my result.
urf core

**Comment by tonysneed** [comment]
@lelong37 Let's install swagger: https://elanderson.net/2017/10/swagger-and-swashbuckle-with-asp-net-core-2/

**Comment by tonysneed** [comment]
So what's going on here is an issue with OData, where properties on the entity marked with `NotMapped` are not serialized.  This can be changed, but we haven't yet configured OData to allow them because the sample is not yet using Trackable Entities.  What's happening is that PATCH is accepting a partial object but doing a full update in the database (without ModifiedProperties being set).

So what we're planning to do is create another sample API that does not use OData, where your Postman client will work just fine. /cc @lelong37

**Pull request closed without merging**
